[package]
name = "lprofile-rs"
version = "0.1.0"
authors = ["Fingercomp <fingercomp@fomalhaut.me>"]
edition = "2018"

[lib]
name = "lprofile_hook"
crate-type = ["dylib"]

[dependencies]
once_cell = "1.4.0"
lua = { path = "./rust-lua53" }
